### ISSUE TITLE
[feature request] Provide api to integrate with fzf-lua

### ISSUE THREAD

**Issue by towry** [mangelozzi/rgflow.nvim#10]
The UI is great, but i'd like to use it with fzf-lua, that means use this as ui lib to collect rg query and args and use fzf-lua to run the search and present the results.

![截屏2024-01-04 16 31 24](https://github.com/mangelozzi/rgflow.nvim/assets/8279858/e1fab396-920c-4319-b7c5-155aa36f0c3c)

The API should be like:

```lua
require('rgflow').open(nil, nil, vim.uv.cwd(), {
 on_enter = function(rgargs)
  local fzf = require('fzf-lua')
  --- .... use fzf to run the search.
end
})
```

fzf-lua provided actions so I can bind keymap to easily toggle between fzf-lua picker and rgflow ui to change the args and run search again.

**Comment by towry** [comment]
<img width="911" alt="截屏2024-01-04 16 38 09" src="https://github.com/mangelozzi/rgflow.nvim/assets/8279858/fcd982b5-fe05-412e-a072-508d01915fd9">

**Comment by mangelozzi** [comment]
Hi, thanks for the positive vibes.

I added an option to allow one to use the UI to collect the pattern/flag/path strings and then pass them into one's own custom function. Please refer to: https://github.com/mangelozzi/rgflow.nvim#open-options

If this meets your requirement, feel free to close the issue, and share some of your set up so we can try out your idea too... else let me know what needs changing.

Cheers mate!

**Comment by towry** [comment]
Hi, thanks for your great work, it works very well. here is a screencast that show it, and here is the usage: https://github.com/search?q=rgflow+fzf-lua+repo%3Atowry%2Fnvim+path%3A*.lua&type=code

https://github.com/towry/nvim/blob/8ee8a6c8ea212e5883f31e003406d018e4304ca0/lua/userlib/fzflua/init.lua#L21


https://github.com/mangelozzi/rgflow.nvim/assets/8279858/79e92a7e-9f01-4cf1-9e3c-0a721a332c8f

And I think maybe it is better to allow empty pattern if user want to use custom_start?

**Comment by mangelozzi** [comment]
Wow nice work there! Thanks for sharing that, very cool!

> And I think maybe it is better to allow empty pattern if user want to use custom_start?

I just tried a few searches with no search pattern, and got a crazy amount of search results, so I don't think it useful for normal Rgflow operation. However I made it such that you can have a blank search pattern if using `custom_start`, which I think will work for you so you can edit the flags/path, and then in fzf adjust the pattern.

Cheers
