### ISSUE TITLE
-g glob flag is not supported

### ISSUE THREAD

**Issue by xixiaofinland** [mangelozzi/rgflow.nvim#11]
When using `-g` flag in the plugin it always returns no result while `rg` in terminal has the correct result.

![Screenshot 2024-01-05 at 11 14 54](https://github.com/mangelozzi/rgflow.nvim/assets/13655323/8dca737e-553b-41d9-af3c-a49d163822a1)

**Comment by xixiaofinland** [comment]
![Screenshot 2024-01-05 at 11 23 08](https://github.com/mangelozzi/rgflow.nvim/assets/13655323/e28cf759-0c6f-4234-ad5b-8693c0a5d7cf)

**Comment by mangelozzi** [comment]
Hey there, thanks for the help in the other issue. 

Try `--smart-case --fixed-strings --ignore --max-columns 200 -g *Test*`

The reason its just `*Test*` and not `'*Test*'` is because it's not the terminal so you don't have to add the quotes to prevent the terminal from interpreting the stars

**Comment by xixiaofinland** [comment]
ahha, ok! Thanks!
