### ISSUE TITLE
Input flags disappear/reappear on every move in normal mode

### ISSUE THREAD

**Issue by kuba-gaj** [mangelozzi/rgflow.nvim#17]
Hi, tried all possible settings in colors (defaults included) and I have this problem that `flags` text disappears (or probably gets set to background color) on every keystroke in `normal` mode.

This doesn't happen on any other field.

Thanks for your work, this is an amazing plugin!

**Comment by mangelozzi** [comment]
Hi, sorry I can't replicate it, to help me diagnose the issue please provide:
1. The color scheme you are using
2. A screen show of the flags disappeared with some of the surrounding file
Cheers!

**Comment by mangelozzi** [comment]
Well I changed to linking hilight groups to the float defaults, hopefully this fixes your issue, if not feel free to provide the above requested info and reopen the issue,
cheers.

**Comment by kuba-gaj** [comment]
I can confirm it fixed my issue. Thank you! I will try to use it more now as I like the idea :)
