### ISSUE TITLE
Document quick highlight colors

### ISSUE THREAD

**Issue by technicalpickles** [mangelozzi/rgflow.nvim#18]
_or, this doesn't look great with https://github.com/folke/tokyonight.nvim_ 😅 

I was pretty excited to install this to get better with rg, or at least expose it more directly to me than I have been with https://github.com/duane9/nvim-rg

It is almost definitely my colorscheme, but the default is really hard to read, and I can't tell where the cursor is:

![CleanShot 2024-04-16 at 08 39 29](https://github.com/mangelozzi/rgflow.nvim/assets/159/234a2a9a-402a-481b-97a5-2e601467e8c1)

I was going to suggest making it the highlight groups configurable, but they are alread 😁  https://github.com/mangelozzi/rgflow.nvim/blob/4d364c39fbbc1112914ca01ba6ace43d177c037f/lua/rgflow/defaults.lua#L123-L140 I think they just need to be mentioned in the read

**Comment by mangelozzi** [comment]
I added this blurb to the [readme](https://github.com/mangelozzi/rgflow.nvim?tab=readme-ov-file#full-configuration-options):

> - The configuration covers
    - Custom highlight colors (colour scheme)
    - Key maps
    - Various other preferences

Let me know if that would have been sufficient for you to find it? If not feel free to recommend changes. The comment has the words `color`, `colour`, `scheme` and `highlight`

Ps this is what Tokyo Night looks like for me by default:
![image](https://github.com/mangelozzi/rgflow.nvim/assets/19764314/9becfcb7-0180-46cf-a20a-363ef5725f5b)

**Comment by technicalpickles** [comment]
Appreciate it, thanks! That is how mine looks, except no cursor... which may be part of my frontend (neovide).
