### ISSUE TITLE
Error in rgflow/colorlib neovim 0.9.2

### ISSUE THREAD

**Issue by phcerdan** [mangelozzi/rgflow.nvim#2]
Hitting the following:

```lua
...ocal/share/nvim/lazy/rgflow.nvim/lua/rgflow/colorlib.lua:29: attempt to compare number with nil

# stacktrace:
  - /rgflow.nvim/lua/rgflow/colorlib.lua:29 _in_ **band**
  - /rgflow.nvim/lua/rgflow/colorlib.lua:44 _in_ **bit24_to_rgb**
  - /rgflow.nvim/lua/rgflow/colorlib.lua:133 _in_ **get_matches_color**
  - /rgflow.nvim/lua/rgflow/settingslib.lua:44 _in_ **get_default_colors**
  - /rgflow.nvim/lua/rgflow/settingslib.lua:61 _in_ **setup_hi_groups**
  - /rgflow.nvim/lua/rgflow/settingslib.lua:106 _in_ **apply_settings**
  - /rgflow.nvim/lua/rgflow/settingslib.lua:144 _in_ **setup**
  - ~/.config/nvim/init.lua:340 _in_ **config**
  - ~/.config/nvim/init.lua:26

```

My config via lazy, in init.lua (the default you provided in README)
```lua
  {
    "mangelozzi/rgflow.nvim",
    config = function()
      require('rgflow').setup {
        -- Set the default rip grep flags and options for when running a search via
        -- RgFlow. Once changed via the UI, the previous search flags are used for
        -- each subsequent search (until Neovim restarts).
        cmd_flags = "--smart-case --fixed-strings --ignore --max-columns 200",
        -- Mappings to trigger RgFlow functions
        default_trigger_mappings = true,
        -- These mappings are only active when the RgFlow UI (panel) is open
        default_ui_mappings = true,
        -- QuickFix window only mapping
        default_quickfix_mappings = true,
      }
    end,
  },

```

nvim --version: 
```
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1694285958

```

**Comment by mangelozzi** [comment]
Thanks for the issue and the nice trace stack. Is it possible that you could please try update the plugin and try again? I see your trace stack has:

```
  - /rgflow.nvim/lua/rgflow/colorlib.lua:133 _in_ **get_matches_color**
 ```

I.e. erroring in function *get_matches_color* on line 133, but in the current release the `colorlib.lua` file the `get_matches_color` function only starts on line [148](
https://github.com/mangelozzi/rgflow.nvim/blob/33212e4fb85e66edbc696cc74c92c85b5204e296/lua/rgflow/colorlib.lua#L148)

**Comment by phcerdan** [comment]
I checked the local files downloaded by lazy, and I got get_matches_color in line 148,as you mentioned. I am not using an outdated plugin. How can I disable the colorlib logic, for testing?

**Comment by phcerdan** [comment]
Ok, if I add the following to the band function, I can workaround that error:

```lua
local function band(a, b)
    if a == nil or b == nil then
        return 0
    end
```

**Comment by mangelozzi** [comment]
Well done for finding a work around, I made a fix, please try it.

PS. all `get_matches_color` does is check if you have the highlight groups "Statement" or "Identifier" and then create a contrasting color based on whether you current background is light or dark. They are built in highlight groups. However if there is an issue calculating the value it now just falls back to using a yellow on dark or a brown on white backgrounds.

**Comment by mangelozzi** [comment]
PS do the updates work for you, can I close the issue?

**Comment by phcerdan** [comment]
They are solved indeed, thanks!
