### ISSUE TITLE
Is there a way of running a callback when the search has finished?

### ISSUE THREAD

**Issue by Ajaymamtora** [mangelozzi/rgflow.nvim#20]
I'd like to extend this function:

```lua
function M.search_literal_string_in_root()
  -- Prompt the user for the search text
  vim.ui.input({ prompt = " Enter the text to search for in root: " }, function(search_text)
    if not search_text or search_text == "" then
      print("Search canceled or search text cannot be empty.")
      return
    end

    -- Perform the search operation
    require("rgflow").search(search_text, "--fixed-strings --no-ignore --hidden", vim.loop.cwd())

    print('Searched all instances of "' .. search_text .. '" in root.')
  end)
end
```

So when the search is finished, I can run :cfdo %s/<search>/<replace>/g ?

Maybe the user could supply a callback, and it could be called from here? https://github.com/mangelozzi/rgflow.nvim/blob/697e90e04cde5caf2a4f394b4375f0f1284c935a/lua/rgflow/search.lua#L36

Im not sure I don't understand the code well enough

**Comment by mangelozzi** [comment]
Hi,
Good idea, please update the plugin, and you can call a custom call back like this:

```lua
        vim.keymap.set("n", "<leader>RG", function()
            require('rgflow').open(nil, nil, nil, {
                callback = function() print('Callback ran... have a nice day!') end
            })
        end, {noremap = true})
```

And of the UI open commands take an option table, and you can set the callback to a function, if supplied, the callback will be run once searching has been completed.
If this does not solve you problem, feel free to open the issue again, cheers!
