### ISSUE TITLE
Error with STATE.path being nil if have not ran rgflow search yet but using a qflist from something else and trying to delete a line

### ISSUE THREAD

**Issue by GitMurf** [mangelozzi/rgflow.nvim#21]
Here is the spot in the code where it is error-ing out: https://github.com/mangelozzi/rgflow.nvim/blob/8a2d80b8594591163d06b430be18c7376d5ae1b8/lua/rgflow/messages.lua#L22

I believe it is because `STATE` starts out with `path` set to nil.

The solution would be to either handle the `nil` check in the messages.lua or just set the default path in your STATE table to be an empty string `''` instead of `nil` (like how the default `pattern` is set).

https://github.com/mangelozzi/rgflow.nvim/blob/8a2d80b8594591163d06b430be18c7376d5ae1b8/lua/rgflow/state.lua#L11-L13

![image](https://github.com/user-attachments/assets/5d2716df-3e2e-4eeb-9d46-8e8cdc2d3fdd)

**Comment by mangelozzi** [comment]
Thanks so much for posting the problem and the solution. This issue has been so well presented it was very easy for me, thank you so much, cheers!

**Comment by GitMurf** [comment]
> Thanks so much for posting the problem and the solution. This issue has been so well presented it was very easy for me, thank you so much, cheers!

Thank YOU for an amazing plugin!
