### ISSUE TITLE
Open visual

### ISSUE THREAD

**Issue by lvim-tech** [mangelozzi/rgflow.nvim#3]
I think open visual not paste visual selection.

**Comment by mangelozzi** [comment]
Thanks for raising the issue. I went through instances of `open_paste` and `open_visual` suspecting maybe I had mixed them up or the documentation, and I could not find any. Would you please provide some more info as to where the mix up is?

From the docs:
| `require('rgflow').open_paste`        | Open UI with first line of unnamed register as pattern.
| `require('rgflow').open_visual`       | Open UI with current visual selection as pattern.

Cheers

**Comment by lvim-tech** [comment]
`require('rgflow').open_visual` - Rgflow has been open but input field is empty

**Comment by mangelozzi** [comment]
Thanks for the extra info, I fixed a bug in the visual selection. It should work now, please let me know.

PS I also improved the behaviour, before if the UI was open, it would not update the pattern if one started a new search, now if the UI is open, if one starts with visual selection, if pattern is blank it will update it. 

Thanks for the find!

**Comment by lvim-tech** [comment]
Thanks, @mangelozzi . Now works perfect!
